In [1]:
import numpy as np
import pandas as pd

In [2]:
d = {'Clubes': [], 'PG': [], 'j': [], 'V': [], 'E': [], 'D': [], 'GP': [], 'GC': [], 'SG': []}
dfClassChampionship = pd.DataFrame(data=d);
dfDataChampionship = pd.read_excel("b2002.xlsx")

In [3]:
dfDataChampionship.head()

,Horario,Dia,Data,Clube 1,Clube 2,Placar,Vencedor,Rodada,Arena
0,NaN,Sábado,10/08/2002,Vasco,Figueirense,2x0,Vasco,1ª Rodada,São Januário
1,NaN,Sábado,10/08/2002,São Paulo,Paysandu,4x2,São Paulo,1ª Rodada,Morumbi
2,NaN,Sábado,10/08/2002,Paraná,São Caetano,2x1,Paraná,1ª Rodada,Couto Pereira
3,NaN,Sábado,10/08/2002,Santos,Botafogo,2x1,Santos,1ª Rodada,Vila Belmiro
4,NaN,Sábado,10/08/2002,Goiás,Portuguesa,3x1,Goiás,1ª Rodada,Serra Dourada

** Get all clubes for championship **

In [4]:
#Cancatenando as colunas Clube 1 e Clube 2
clubs  =  pd.concat([dfDataChampionship['Clube 1'].str.lower(), dfDataChampionship['Clube 2'].str.lower()], axis=1, keys=['Clubes'])

In [5]:
#Obtem todos os clubes 
cb = pd.DataFrame({'Clubes': clubs['Clubes'].unique()})

In [6]:
#Todos os clubes que participaram dp campeonato
cb

           Clubes
0           vasco
1       são paulo
2          paraná
3          santos
4           goiás
5      fluminense
6       palmeiras
7     atlético-mg
8   internacional
9         guarani
10       coritiba
11          bahia
12      juventude
13    são caetano
14       botafogo
15       cruzeiro
16         grêmio
17    atlético-pr
18    figueirense
19    ponte preta
20        vitória
21    corinthians
22       flamengo
23     portuguesa
24           gama
25       paysandu
26            NaN

In [7]:
def getNumberWinner(data, clube ):
    filter = data["Vencedor"].str.lower() == clube
    return (data[filter]['Vencedor'].count()).astype(np.int64)

def getNumberDepartures(data, clube ):
    filter1 = data["Clube 1"].str.lower() == clube
    filter2 = data["Clube 2"].str.lower() == clube
    return (data[filter1]['Clube 1'].count() + data[filter2]['Clube 2'].count()).astype(np.int64)

def getPoints(data, clube ):
    filter1 = data["Clube 1"].str.lower() == clube
    filter2 = data["Clube 2"].str.lower() == clube
    filter3 = data["Vencedor"].str.lower() == clube
    filter4 = (data["Clube 1"].str.lower() == clube) | (data["Clube 2"].str.lower() == clube)
    filter5 = data["Vencedor"].str.lower() == '-'
    
    v1 = data[(filter1) & (filter3)]
    v1 = v1['Vencedor'].count()
    v2 = data[(filter2) & (filter3)]
    v2 = v2['Vencedor'].count() 
    v3 = data[(filter4) & (filter5)]
    v3 = v3['Vencedor'].count()    
    return ((v2*3)+(v1*3)+v3).astype(np.int64)

def getDraw(data, clube ):
    filter1 = (data["Clube 1"].str.lower() == clube) | (data["Clube 2"].str.lower() == clube)
    filter2 = data["Vencedor"].str.lower() == '-'
    df = data[(filter1) & (filter2)]
    empates = df['Vencedor'].count()
    return empates.astype(np.int64)

def getDefeats(data, clube ):
    filter1 = (data["Clube 1"].str.lower() == clube) | (data["Clube 2"].str.lower() == clube)
    filter2 = (data["Vencedor"].str.lower() != clube) & (data["Vencedor"].str.lower() != '-')
    df = data[(filter1) & (filter2)]
    derrotas = df['Vencedor'].count()
    return derrotas.astype(np.int64)

def getGP(data, clube ):
    filter1  =  data["Clube 1"].str.lower() == clube
    filter2  =  data["Clube 2"].str.lower() == clube
    df1      =  data[(filter1)]
    df2      =  data[(filter2)]
    placar1  =  df1['Placar'].str.split('x')
    placar2  =  df2['Placar'].str.split('x')
    gp       =  0
    gc       =  0
    for g1, g2 in placar1:
        gp = (gp + pd.to_numeric( g1 ))
        gc = (gc + pd.to_numeric( g2 ))
            
    for g1, g2 in placar2:
        gp = (gp + pd.to_numeric( g2 )) 
        gc = (gc + pd.to_numeric( g1 ))
    return gp, gc

In [8]:
dfTable = cb[["Clubes"]].copy()

for column in ["PG", "J", "V", "E", "D", "GP", "GC", "SG"]:
    dfTable[column] = pd.np.nan
    
for index, row in dfTable.iterrows():
    gp, gc   =  getGP(dfDataChampionship, row["Clubes"] )
    
    dfTable.at[index, 'PG'] = getPoints(dfDataChampionship, row["Clubes"] )
    dfTable.at[index, 'J']  = getNumberDepartures(dfDataChampionship, row["Clubes"] )
    dfTable.at[index, 'V']  = getNumberWinner(dfDataChampionship, row["Clubes"] )    
    dfTable.at[index, 'E']  = getDraw(dfDataChampionship, row["Clubes"] )
    dfTable.at[index, 'D']  = getDefeats(dfDataChampionship, row["Clubes"] )
    dfTable.at[index, 'GP'] = gp
    dfTable.at[index, 'GC'] = gc
    dfTable.at[index, 'SG'] = gp - gc

In [9]:
reorderlist = ['Santos', 'Corinthians', 'Grêmio', 'Fluminense', 'São Paulo', 'São Caetano', 'Juventude', 
               'Atlético-mg', 'Cruzeiro', 'Vitória', 'Coritiba', 'Goiás', 'Ponte Preta', 'Atlético-pr', 
               'Vasco', 'Guarani', 'Figueirense', 'Flamengo', 'Bahia', 'Paysandu', 'Internacional', 
               'Paraná', 'Portuguesa', 'Palmeiras', 'Gama', 'Botafogo']
listIndex   = []

#Processa a lista para gerar a lista de ordenação
for clube in reorderlist:
    for index, row in dfTable.iterrows():
        #Verifica se o valor de clube é um unicode, se não, convete isso.
        if type(clube) != unicode:
            c =  clube.decode('utf-8')
        else:
            c =  clube
        
        c  =  c.lower()
        
        #Verifica se o clube iterado é igual ao clube da lista, se sim
        #retorna seu indice
        if row['Clubes'] == c:
            listIndex.append( index )
            break

            
#Reordena a lista
dfTable  =  dfTable.reindex(index=listIndex, columns=["Clubes", "PG", "J", "V", "E", "D", "GP", "GC", "SG"])
#Com a lista ordenada, corrige os indices.
dfTable.index =  np.arange(1, len(dfTable)+1)
dfTable

           Clubes    PG     J     V    E     D    GP    GC    SG
1          santos  54.0  31.0  16.0  6.0   9.0  59.0  41.0  18.0
2     corinthians  52.0  31.0  15.0  7.0   9.0  50.0  46.0   4.0
3          grêmio  48.0  29.0  13.0  9.0   7.0  41.0  31.0  10.0
4      fluminense  46.0  29.0  14.0  4.0  11.0  49.0  51.0  -2.0
5       são paulo  52.0  27.0  16.0  4.0   7.0  59.0  40.0  19.0
6     são caetano  50.0  27.0  15.0  5.0   7.0  44.0  31.0  13.0
7       juventude  41.0  26.0  12.0  5.0   9.0  33.0  30.0   3.0
8     atlético-mg  40.0  27.0  12.0  4.0  11.0  52.0  51.0   1.0
9        cruzeiro  36.0  25.0  10.0  6.0   9.0  39.0  41.0  -2.0
10        vitória  37.0  25.0  11.0  4.0  10.0  46.0  42.0   4.0
11       coritiba  36.0  25.0  11.0  3.0  11.0  34.0  34.0   0.0
12          goiás  39.0  25.0  11.0  6.0   8.0  42.0  36.0   6.0
13    ponte preta  37.0  26.0  11.0  4.0  11.0  37.0  34.0   3.0
14    atlético-pr  34.0  25.0   9.0  7.0   9.0  39.0  33.0   6.0
15          vasco  30.0  25.0   9.0  3.0  13.0  34.0  38.0  -4.0
16        guarani  32.0  24.0   9.0  5.0  10.0  29.0  33.0  -4.0
17    figueirense  31.0  25.0   9.0  4.0  12.0  34.0  43.0  -9.0
18       flamengo  29.0  24.0   8.0  5.0  11.0  36.0  37.0  -1.0
19          bahia  30.0  25.0   8.0  6.0  11.0  35.0  37.0  -2.0
20       paysandu  29.0  25.0   9.0  2.0  14.0  35.0  46.0 -11.0
21  internacional  29.0  24.0   7.0  8.0   9.0  36.0  36.0   0.0
22         paraná  28.0  25.0   8.0  4.0  13.0  37.0  42.0  -5.0
23     portuguesa  26.0  24.0   7.0  5.0  12.0  25.0  39.0 -14.0
24      palmeiras  27.0  25.0   6.0  9.0  10.0  37.0  46.0  -9.0
25           gama  25.0  25.0   7.0  4.0  14.0  30.0  39.0  -9.0
26       botafogo  25.0  25.0   6.0  7.0  12.0  24.0  39.0 -15.0

** Diversos clubes apresentando valores divergentes na fonte de onde os dados foram exgtraidos, na tabela da fonte é apresentado um resultado, na contagem dos jogos é apresentado outro resultado. **