In [4]:
import numpy as np
import pandas as pd

In [57]:
d = {'Clubes': [], 'PG': [], 'j': [], 'V': [], 'E': [], 'D': [], 'GP': [], 'GC': [], 'SG': []}
dfClassChampionship = pd.DataFrame(data=d);
dfDataChampionship = pd.read_excel("b2019.xlsx", encoding='utf8')

In [58]:
dfDataChampionship.head()

,Horario,Dia,Data,Clube 1,Clube 2,Placar,Vencedor,Rodada,Arena
0,20:00,Segunda-feira,27/05/2019,Avaí,Ceará,1 x 2,Ceará,0ª Rodada,Ressacada
1,20:00,Segunda-feira,27/05/2019,CSA,Goiás,1 x 0,CSA,0ª Rodada,Rei Pelé
2,16:00,Sábado,27/04/2019,São Paulo,Botafogo-rj,2 x 0,São Paulo,1ª Rodada,Morumbi
3,19:00,Sábado,27/04/2019,Chapecoense,Internacional,2 x 0,Chapecoense,1ª Rodada,Arena Condá
4,19:00,Sábado,27/04/2019,Atlético-MG,Avaí,2 x 1,Atlético-MG,1ª Rodada,Independência

** Get all clubes for championship **

In [59]:
#Cancatenando as colunas Clube 1 e Clube 2
clubs  =  pd.concat([dfDataChampionship['Clube 1'].str.lower(), dfDataChampionship['Clube 2'].str.lower()], axis=1, keys=['Clubes'])

In [60]:
#Obtem todos os clubes 
cb = pd.DataFrame({'Clubes': clubs['Clubes'].unique()})

In [61]:
#Todos os clubes que participaram dp campeonato
cb

           Clubes
0            avaí
1             csa
2       são paulo
3     chapecoense
4     atlético-mg
5        flamengo
6          grêmio
7           ceará
8    athlético-pr
9           bahia
10     fluminense
11      palmeiras
12  internacional
13    corinthians
14       cruzeiro
15      fortaleza
16          vasco
17          goiás
18         santos
19    botafogo-rj

In [62]:
def getNumberWinner(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter = df["Vencedor"].str.lower() == clube
    return (data[filter]['Vencedor'].count()).astype(np.int64)

def getNumberDepartures(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = df["Clube 1"].str.lower() == clube
    filter2 = df["Clube 2"].str.lower() == clube
    return (data[filter1]['Clube 1'].count() + data[filter2]['Clube 2'].count()).astype(np.int64)

def getPoints(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = df["Clube 1"].str.lower() == clube
    filter2 = df["Clube 2"].str.lower() == clube
    filter3 = df["Vencedor"].str.lower() == clube
    filter4 = (df["Clube 1"].str.lower() == clube) | (df["Clube 2"].str.lower() == clube)
    filter5 = df["Vencedor"].str.lower() == '-'
    
    v1 = data[(filter1) & (filter3)]
    v1 = v1['Vencedor'].count()
    v2 = data[(filter2) & (filter3)]
    v2 = v2['Vencedor'].count() 
    v3 = data[(filter4) & (filter5)]
    v3 = v3['Vencedor'].count()
    return ((v2*3)+(v1*3)+v3).astype(np.int64)

def getDraw(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = (df["Clube 1"].str.lower() == clube) | (df["Clube 2"].str.lower() == clube)
    filter2 = df["Vencedor"].str.lower() == '-'
    df = data[(filter1) & (filter2)]
    empates = df['Vencedor'].count()
    return empates.astype(np.int64)

def getDefeats(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = (df["Clube 1"].str.lower() == clube) | (df["Clube 2"].str.lower() == clube)
    filter2 = (df["Vencedor"].str.lower() != clube) & (df["Vencedor"].str.lower() != '-')
    df = data[(filter1) & (filter2)]
    derrotas = df['Vencedor'].count()
    return derrotas.astype(np.int64)

def getGP(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1  =  df["Clube 1"].str.lower() == clube
    filter2  =  df["Clube 2"].str.lower() == clube
    df1      =  data[(filter1)]
    df2      =  data[(filter2)]
    placar1  =  df1['Placar'].str.split('x')
    placar2  =  df2['Placar'].str.split('x')
    gp       =  0
    gc       =  0
    for g1, g2 in placar1:
        gp = (gp + pd.to_numeric( g1 ))
        gc = (gc + pd.to_numeric( g2 ))
            
    for g1, g2 in placar2:
        gp = (gp + pd.to_numeric( g2 )) 
        gc = (gc + pd.to_numeric( g1 ))
    return gp, gc

In [63]:
dfTable = cb[["Clubes"]].copy()
for column in ["PG", "J", "V", "E", "D", "GP", "GC", "SG"]:
    dfTable[column] = pd.np.nan

def ensureUtf(s, encoding='utf8'):
  """Converts input to unicode if necessary.

  If `s` is bytes, it will be decoded using the `encoding` parameters.

  This function is used for preprocessing /source/ and /filename/ arguments
  to the builtin function `compile`.
  """
  # In Python2, str == bytes.
  # In Python3, bytes remains unchanged, but str means unicode
  # while unicode is not defined anymore
  if type(s) == bytes:
    return s.decode(encoding, 'ignore')
  else:
    return s     
    
for index, row in dfTable.iterrows():
    c1  =  row['Clubes']
    c1  =  ensureUtf( c1 )
    c1  =  c1.strip()
    
    pg       =  getPoints(dfDataChampionship, c1 )
    j        =  getNumberDepartures(dfDataChampionship, c1 )
    v        =  getNumberWinner(dfDataChampionship, c1 )
    e        =  getDraw(dfDataChampionship, c1 )
    d        =  getDefeats(dfDataChampionship, c1 )
    gp, gc   =  getGP(dfDataChampionship, c1 )
    
    
    dfTable.at[index, 'PG'] = pg
    dfTable.at[index, 'J']  = j
    dfTable.at[index, 'V']  = v
    dfTable.at[index, 'E']  = e
    dfTable.at[index, 'D']  = d
    dfTable.at[index, 'GP'] = gp
    dfTable.at[index, 'GC'] = gc
    dfTable.at[index, 'SG'] = gp - gc
    
    #print c1

dfTable

           Clubes    PG     J     V     E     D    GP    GC    SG
0            avaí  20.0  38.0   3.0  11.0  24.0  18.0  62.0 -44.0
1             csa  32.0  38.0   8.0   8.0  22.0  24.0  58.0 -34.0
2       são paulo  63.0  38.0  17.0  12.0   9.0  39.0  30.0   9.0
3     chapecoense  32.0  38.0   7.0  11.0  20.0  31.0  52.0 -21.0
4     atlético-mg  48.0  38.0  13.0   9.0  16.0  45.0  49.0  -4.0
5        flamengo  90.0  38.0  28.0   6.0   4.0  86.0  37.0  49.0
6          grêmio  65.0  38.0  19.0   8.0  11.0  64.0  39.0  25.0
7           ceará  39.0  38.0  10.0   9.0  19.0  36.0  41.0  -5.0
8    athlético-pr  64.0  38.0  18.0  10.0  10.0  51.0  32.0  19.0
9           bahia  49.0  38.0  12.0  13.0  13.0  44.0  43.0   1.0
10     fluminense  46.0  38.0  12.0  10.0  16.0  38.0  46.0  -8.0
11      palmeiras  74.0  38.0  21.0  11.0   6.0  61.0  32.0  29.0
12  internacional  57.0  38.0  16.0   9.0  13.0  44.0  39.0   5.0
13    corinthians  56.0  38.0  14.0  14.0  10.0  42.0  34.0   8.0
14       cruzeiro  36.0  38.0   7.0  15.0  16.0  27.0  46.0 -19.0
15      fortaleza  53.0  38.0  15.0   8.0  15.0  50.0  49.0   1.0
16          vasco  49.0  38.0  12.0  13.0  13.0  39.0  45.0  -6.0
17          goiás  52.0  38.0  15.0   7.0  16.0  46.0  64.0 -18.0
18         santos  74.0  38.0  22.0   8.0   8.0  60.0  33.0  27.0
19    botafogo-rj  43.0  38.0  13.0   4.0  21.0  31.0  45.0 -14.0

In [64]:
reorderlist = [   "flamengo", "santos", "palmeiras", "grêmio", "athlético-pr", "são paulo", 
                  "internacional", "corinthians", "fortaleza", "goiás", "bahia", "vasco", "atlético-mg", 
                  "fluminense", "botafogo-rj", "ceará", "cruzeiro", "csa", "chapecoense", "avaí"
              ]
listIndex   = []

#Processa a lista para gerar a lista de ordenação
for clube in reorderlist:
    for index, row in dfTable.iterrows():
        #Verifica se o valor de clube é um unicode, se não, convete isso.
        c   =  ensureUtf( clube )
        
        c1  =  row['Clubes']
        #print c1
        c1  =  ensureUtf( c1 )
        
        c1 =  c1.strip()
        c  =  c.lower()
        
        #Verifica se o clube iterado é igual ao clube da lista, se sim
        #retorna seu indice
        if c1 == c:
            listIndex.append( index )
            
#Reordena a lista
dfTable  =  dfTable.reindex(index=listIndex, columns=["Clubes", "PG", "J", "V", "E", "D", "GP", "GC", "SG"])
#Com a lista ordenada, corrige os indices.
dfTable.index =  np.arange(1, len(dfTable)+1)
dfTable

           Clubes    PG     J     V     E     D    GP    GC    SG
1        flamengo  90.0  38.0  28.0   6.0   4.0  86.0  37.0  49.0
2          santos  74.0  38.0  22.0   8.0   8.0  60.0  33.0  27.0
3       palmeiras  74.0  38.0  21.0  11.0   6.0  61.0  32.0  29.0
4          grêmio  65.0  38.0  19.0   8.0  11.0  64.0  39.0  25.0
5    athlético-pr  64.0  38.0  18.0  10.0  10.0  51.0  32.0  19.0
6       são paulo  63.0  38.0  17.0  12.0   9.0  39.0  30.0   9.0
7   internacional  57.0  38.0  16.0   9.0  13.0  44.0  39.0   5.0
8     corinthians  56.0  38.0  14.0  14.0  10.0  42.0  34.0   8.0
9       fortaleza  53.0  38.0  15.0   8.0  15.0  50.0  49.0   1.0
10          goiás  52.0  38.0  15.0   7.0  16.0  46.0  64.0 -18.0
11          bahia  49.0  38.0  12.0  13.0  13.0  44.0  43.0   1.0
12          vasco  49.0  38.0  12.0  13.0  13.0  39.0  45.0  -6.0
13    atlético-mg  48.0  38.0  13.0   9.0  16.0  45.0  49.0  -4.0
14     fluminense  46.0  38.0  12.0  10.0  16.0  38.0  46.0  -8.0
15    botafogo-rj  43.0  38.0  13.0   4.0  21.0  31.0  45.0 -14.0
16          ceará  39.0  38.0  10.0   9.0  19.0  36.0  41.0  -5.0
17       cruzeiro  36.0  38.0   7.0  15.0  16.0  27.0  46.0 -19.0
18            csa  32.0  38.0   8.0   8.0  22.0  24.0  58.0 -34.0
19    chapecoense  32.0  38.0   7.0  11.0  20.0  31.0  52.0 -21.0
20           avaí  20.0  38.0   3.0  11.0  24.0  18.0  62.0 -44.0