In [1]:
import numpy as np
import pandas as pd

In [2]:
d = {'Clubes': [], 'PG': [], 'j': [], 'V': [], 'E': [], 'D': [], 'GP': [], 'GC': [], 'SG': []}
dfClassChampionship = pd.DataFrame(data=d);
dfDataChampionship = pd.read_excel("b2015.xlsx", encoding='utf8')

In [3]:
dfDataChampionship.head()

,Horario,Dia,Data,Clube 1,Clube 2,Placar,Vencedor,Rodada,Arena
0,18h30,Sábado,19/04/2014,Fluminense,Figueirense,3x0,Fluminense,1ª Rodada,Maracanã
1,18h30,Sábado,19/04/2014,Internacional,Vitória,1x0,Internacional,1ª Rodada,Beira Rio
2,21h00,Sábado,19/04/2014,Chapecoense,Coritiba,0x0,-,1ª Rodada,Arena Condá
3,16h00,Domingo,20/04/2014,Atlético-MG,Corinthians,0x0,-,1ª Rodada,Parque do Sabiá
4,16h00,Domingo,20/04/2014,Atlético-PR,Grêmio,1x0,Atlético-PR,1ª Rodada,Orlando Scarpelli

** Get all clubes for championship **

In [4]:
#Cancatenando as colunas Clube 1 e Clube 2
clubs  =  pd.concat([dfDataChampionship['Clube 1'].str.lower(), dfDataChampionship['Clube 2'].str.lower()], axis=1, keys=['Clubes'])

In [5]:
#Obtem todos os clubes 
cb = pd.DataFrame({'Clubes': clubs['Clubes'].unique()})

In [6]:
#Todos os clubes que participaram dp campeonato
cb

           Clubes
0      fluminense
1   internacional
2     chapecoense
3     atlético-mg
4     atlético-pr
5       são paulo
6           bahia
7          santos
8        flamengo
9        criciúma
10       coritiba
11      palmeiras
12       botafogo
13       cruzeiro
14        vitória
15    corinthians
16          goiás
17          sport
18    figueirense
19         grêmio

In [7]:
def getNumberWinner(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter = df["Vencedor"].str.lower() == clube
    return (data[filter]['Vencedor'].count()).astype(np.int64)

def getNumberDepartures(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = df["Clube 1"].str.lower() == clube
    filter2 = df["Clube 2"].str.lower() == clube
    return (data[filter1]['Clube 1'].count() + data[filter2]['Clube 2'].count()).astype(np.int64)

def getPoints(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = df["Clube 1"].str.lower() == clube
    filter2 = df["Clube 2"].str.lower() == clube
    filter3 = df["Vencedor"].str.lower() == clube
    filter4 = (df["Clube 1"].str.lower() == clube) | (df["Clube 2"].str.lower() == clube)
    filter5 = df["Vencedor"].str.lower() == '-'
    
    v1 = data[(filter1) & (filter3)]
    v1 = v1['Vencedor'].count()
    v2 = data[(filter2) & (filter3)]
    v2 = v2['Vencedor'].count() 
    v3 = data[(filter4) & (filter5)]
    v3 = v3['Vencedor'].count()
    return ((v2*3)+(v1*3)+v3).astype(np.int64)

def getDraw(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = (df["Clube 1"].str.lower() == clube) | (df["Clube 2"].str.lower() == clube)
    filter2 = df["Vencedor"].str.lower() == '-'
    df = data[(filter1) & (filter2)]
    empates = df['Vencedor'].count()
    return empates.astype(np.int64)

def getDefeats(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1 = (df["Clube 1"].str.lower() == clube) | (df["Clube 2"].str.lower() == clube)
    filter2 = (df["Vencedor"].str.lower() != clube) & (df["Vencedor"].str.lower() != '-')
    df = data[(filter1) & (filter2)]
    derrotas = df['Vencedor'].count()
    return derrotas.astype(np.int64)

def getGP(data, clube ):
    df = data.apply(lambda x: x.str.strip())
    filter1  =  df["Clube 1"].str.lower() == clube
    filter2  =  df["Clube 2"].str.lower() == clube
    df1      =  data[(filter1)]
    df2      =  data[(filter2)]
    placar1  =  df1['Placar'].str.split('x')
    placar2  =  df2['Placar'].str.split('x')
    gp       =  0
    gc       =  0
    for g1, g2 in placar1:
        gp = (gp + pd.to_numeric( g1 ))
        gc = (gc + pd.to_numeric( g2 ))
            
    for g1, g2 in placar2:
        gp = (gp + pd.to_numeric( g2 )) 
        gc = (gc + pd.to_numeric( g1 ))
    return gp, gc

In [8]:
dfTable = cb[["Clubes"]].copy()
for column in ["PG", "J", "V", "E", "D", "GP", "GC", "SG"]:
    dfTable[column] = pd.np.nan
    
    
for index, row in dfTable.iterrows():
    c1  =  row['Clubes']
    if type(c1) != unicode:
        c1 =  c1.decode('utf-8')
    c1 =  c1.strip()
    
    pg       =  getPoints(dfDataChampionship, c1 )
    j        =  getNumberDepartures(dfDataChampionship, c1 )
    v        =  getNumberWinner(dfDataChampionship, c1 )
    e        =  getDraw(dfDataChampionship, c1 )
    d        =  getDefeats(dfDataChampionship, c1 )
    gp, gc   =  getGP(dfDataChampionship, c1 )
    
    if c1 == u'grêmio prudente':
        pg -= 3
    
    dfTable.at[index, 'PG'] = pg
    dfTable.at[index, 'J']  = j
    dfTable.at[index, 'V']  = v
    dfTable.at[index, 'E']  = e
    dfTable.at[index, 'D']  = d
    dfTable.at[index, 'GP'] = gp
    dfTable.at[index, 'GC'] = gc
    dfTable.at[index, 'SG'] = gp - gc
    
    #print c1

dfTable

           Clubes    PG     J     V     E     D    GP    GC    SG
0      fluminense  61.0  38.0  17.0  10.0  11.0  61.0  42.0  19.0
1   internacional  69.0  38.0  21.0   6.0  11.0  53.0  41.0  12.0
2     chapecoense  43.0  38.0  11.0  10.0  17.0  39.0  44.0  -5.0
3     atlético-mg  62.0  38.0  17.0  11.0  10.0  51.0  38.0  13.0
4     atlético-pr  54.0  38.0  15.0   9.0  14.0  43.0  42.0   1.0
5       são paulo  70.0  38.0  20.0  10.0   8.0  59.0  40.0  19.0
6           bahia  37.0  38.0   9.0  10.0  19.0  31.0  43.0 -12.0
7          santos  53.0  38.0  15.0   8.0  15.0  42.0  35.0   7.0
8        flamengo  52.0  38.0  14.0  10.0  14.0  46.0  47.0  -1.0
9        criciúma  32.0  38.0   7.0  11.0  20.0  28.0  56.0 -28.0
10       coritiba  47.0  38.0  12.0  11.0  15.0  42.0  45.0  -3.0
11      palmeiras  40.0  38.0  11.0   7.0  20.0  34.0  59.0 -25.0
12       botafogo  34.0  38.0   9.0   7.0  22.0  31.0  48.0 -17.0
13       cruzeiro  80.0  38.0  24.0   8.0   6.0  67.0  38.0  29.0
14        vitória  38.0  38.0  10.0   8.0  20.0  37.0  54.0 -17.0
15    corinthians  69.0  38.0  19.0  12.0   7.0  49.0  31.0  18.0
16          goiás  47.0  38.0  13.0   8.0  17.0  38.0  40.0  -2.0
17          sport  52.0  38.0  14.0  10.0  14.0  36.0  46.0 -10.0
18    figueirense  47.0  38.0  13.0   8.0  17.0  37.0  47.0 -10.0
19         grêmio  61.0  38.0  17.0  10.0  11.0  36.0  24.0  12.0

In [9]:
reorderlist = [   "CRUZEIRO", "SÃO PAULO", "INTERNACIONAL", "CORINTHIANS", "ATLÉTICO-MG", 
                  "FLUMINENSE", "GRÊMIO", "ATLÉTICO-PR", "SANTOS", "FLAMENGO", "SPORT", "GOIÁS",
                  "FIGUEIRENSE", "CORITIBA", "CHAPECOENSE", "PALMEIRAS", "VITÓRIA",
                  "BAHIA", "BOTAFOGO-RJ", "CRICIÚMA"
              ]
listIndex   = []

#Processa a lista para gerar a lista de ordenação
for clube in reorderlist:
    for index, row in dfTable.iterrows():
        #Verifica se o valor de clube é um unicode, se não, convete isso.
        if type(clube) != unicode:
            c =  clube.decode('utf-8')
        else:
            c =  clube
        
        c1  =  row['Clubes']
        #print c1
        if type(c1) != unicode:
            c1 =  c1.decode('utf-8')
        
        c1 =  c1.strip()
        c  =  c.lower()
        
        #Verifica se o clube iterado é igual ao clube da lista, se sim
        #retorna seu indice
        if c1 == c:
            listIndex.append( index )
        elif (c == 'botafogo-rj') & (c1 == 'botafogo'):
            listIndex.append( index )
            break
            
#Reordena a lista
dfTable  =  dfTable.reindex(index=listIndex, columns=["Clubes", "PG", "J", "V", "E", "D", "GP", "GC", "SG"])
#Com a lista ordenada, corrige os indices.
dfTable.index =  np.arange(1, len(dfTable)+1)
dfTable

           Clubes    PG     J     V     E     D    GP    GC    SG
1        cruzeiro  80.0  38.0  24.0   8.0   6.0  67.0  38.0  29.0
2       são paulo  70.0  38.0  20.0  10.0   8.0  59.0  40.0  19.0
3   internacional  69.0  38.0  21.0   6.0  11.0  53.0  41.0  12.0
4     corinthians  69.0  38.0  19.0  12.0   7.0  49.0  31.0  18.0
5     atlético-mg  62.0  38.0  17.0  11.0  10.0  51.0  38.0  13.0
6      fluminense  61.0  38.0  17.0  10.0  11.0  61.0  42.0  19.0
7          grêmio  61.0  38.0  17.0  10.0  11.0  36.0  24.0  12.0
8     atlético-pr  54.0  38.0  15.0   9.0  14.0  43.0  42.0   1.0
9          santos  53.0  38.0  15.0   8.0  15.0  42.0  35.0   7.0
10       flamengo  52.0  38.0  14.0  10.0  14.0  46.0  47.0  -1.0
11          sport  52.0  38.0  14.0  10.0  14.0  36.0  46.0 -10.0
12          goiás  47.0  38.0  13.0   8.0  17.0  38.0  40.0  -2.0
13    figueirense  47.0  38.0  13.0   8.0  17.0  37.0  47.0 -10.0
14       coritiba  47.0  38.0  12.0  11.0  15.0  42.0  45.0  -3.0
15    chapecoense  43.0  38.0  11.0  10.0  17.0  39.0  44.0  -5.0
16      palmeiras  40.0  38.0  11.0   7.0  20.0  34.0  59.0 -25.0
17        vitória  38.0  38.0  10.0   8.0  20.0  37.0  54.0 -17.0
18          bahia  37.0  38.0   9.0  10.0  19.0  31.0  43.0 -12.0
19       botafogo  34.0  38.0   9.0   7.0  22.0  31.0  48.0 -17.0
20       criciúma  32.0  38.0   7.0  11.0  20.0  28.0  56.0 -28.0

** Por algum motivo que desconheço, na fonte dos dados o Vitória possui 39 pontos, na soma dos jogos, resulta em 38. **